services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cardinal
      - POSTGRES_PASSWORD=cardinal
      - POSTGRES_DB=cardinal
      - DB_NAMESPACE=auth
    networks:
      - cardinal

networks:
  cardinal:
