services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./init_postgres.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_USER=cardinal
      - POSTGRES_PASSWORD=cardinal
      - POSTGRES_DB=cardinal
      - DB_NAMESPACE=auth
    networks:
      - cardinal

networks:
  cardinal:
